services:
  postgres:
    container_name: calendar
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: calendar
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: calendar
    ports:
      - 5435:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
volumes: 
  postgres-data: